---
fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib"
    postgresql: "git://github.com/puppetlabs/puppetlabs-postgresql"
    cron_core: "git://github.com/puppetlabs/puppetlabs-cron_core"
